#!/bin/bash
git add . #komandu "uzmanāmo" mapju pievienošanai
git config --global user.name Valers0412
git config --global user.email valters.robo@gmail.com
git commit -m "Class_04a"
git push origin main
